<?php

$default_data = Array(
	"tie_options"	=> Array(
		'breadcrumbs' 				=> 		true,
		'breadcrumbs_delimiter' 	=> 		'/',
		'lightbox_style' 			=> 		'light_rounded',
		'exc_length' 				=> 		'10',
		'on_home' 					=> 		'grid',
		'post_width' 				=> 		'2',
		'enable_filter' 			=> 		true,
		'show_meta' 				=> 		true,
		'show_comments' 			=> 		true,
		'grid_pagination'			=>		'button',
		'num_comments' 				=> 		'3',
		'logo_setting' 				=> 		'logo',
		'logo_margin' 				=> 		'0',
		'header_layout' 			=> 		'2',
		'welcome_box' 				=> 		false,
		'welcome_display' 			=> 		'1',
		'welcome_msg' 				=> 		'<h2>Welcome to Remal</h2><p>Change this text From Tiepanel > Header Settings !</p>',
		'sidebar_pos' 				=> 		'right',
		'post_authorbio' 			=> 		true,
		'post_nav' 					=> 		true,
		'post_meta' 				=> 		true,
		'post_author' 				=> 		true,
		'post_date' 				=> 		true,
		'post_cats' 				=> 		true,
		'post_views' 				=> 		true,
		'post_likes' 				=> 		true,
		'post_comments' 			=> 		true,
		'post_tags' 				=> 		true,
		'share_post' 				=> 		true,
		'share_tweet' 				=> 		true,
		'share_facebook' 			=> 		true,
		'share_google' 				=> 		true,
		'share_linkdin'				=> 		true,
		'share_stumble' 			=> 		true,
		'share_pinterest' 			=> 		true,
		'related' 					=> 		false,
		'related_number' 			=> 		'3',
		'related_query' 			=> 		'category',
		'footer_top' 				=> 		true,
		'footer_social' 			=> 		true,
		'footer_widgets' 			=> 		'footer-3c',
		'footer_one' 				=> 		'&#169; Copyright 2012, All Rights Reserved',
		'footer_two' 				=> 		'Powered by <a href="http://www.wordpress.com">WordPress</a> | Designed by <a href="http://www.tielabs.com">Tielabs</a>',
		'category_desc' 			=> 		true,
		'category_rss' 				=> 		true,
		'tag_rss' 					=> 		true,
		'author_bio' 				=> 		true,
		'author_rss' 				=> 		true,
		'background_type' 			=> 		'pattern',
		'notify_theme' 				=> 		true
	)
);

?>